- name: restart monit
  become: true
  service:
    name: monit
    state: restarted

- name: do reload monit
  become: true
  service:
    name: monit
    state: reloaded
  listen: reload monit

- name: wait for monit to restart
  pause:
    seconds: 5
  listen: reload monit

