nginx_worker_processes: "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
nginx_worker_connections: "768"
nginx_keepalive_timeout: "65"
nginx_remove_default_vhost: true
nginx_user: "www-data"

puma_workers: "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
