- name: Include vars for dependencies
  include_vars:
    file: '../puma/defaults/main.yml'

- name: Add nodesource key
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add nodesource package
  become: yes
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{node_version}}.x xenial main
    state: present

- name: Install dependencies for gems
  become: yes
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - libpq-dev
    - nodejs

- name: Install npm modules
  become: yes
  npm:
    name: "{{item}}"
    global: yes
  with_items:
    - yarn

- name: 'Create current version directory: {{app_directory}}'
  become: true
  file:
    path: "{{app_directory}}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0755

- name: 'Add profile.d file'
  become: true
  template:
    src: app-profile.sh.j2
    dest: '/etc/profile.d/{{app_name}}.sh'

- name: Enable access from nginx
  become: true
  ufw:
    rule: allow
    port: 3000
    src: '{{ item }}'
  with_items: "{{groups.nginx}}"
