- name: Apt-get update
  become: true
  apt:
    update_cache: yes

- name: Configure open ports
  become: true
  ufw:
    rule: "{{item.rule}}"
    port: "{{item.port}}"
    proto: "{{item.proto}}"
  with_items:
    - {rule: 'allow', port: 22, proto: 'tcp'}
    - {rule: 'allow', port: 123, proto: 'udp'}

- name: Configure default incoming/outgoing rules with ufw
  become: true
  ufw:
    direction: "{{item.direction}}"
    policy: "{{item.policy}}"
    state: enabled
  with_items:
    - {direction: outgoing, policy: allow}
    - {direction: incoming, policy: deny}

- name: Ensure app directory exists and is writeable.
  become: true
  file:
    path: "{{item}}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0755
  with_items:
    - "{{ app_directory }}"
    - "{{ app_shared_directory }}"
    - "{{ app_logs_directory }}"
    - "{{ app_tmp_directory }}"
    - "{{ app_pids_directory }}"
    - "{{ app_bin_directory }}"
